// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCore_Lab_03.Models;

[Table("Department")]
public partial class Department
{
    [Key]
    [Column("Dept_Id")]
    public int DeptId { get; set; }

    [Column("Dept_Name")]
    [StringLength(50)]
    public string? DeptName { get; set; }

    [Column("Dept_Desc")]
    [StringLength(100)]
    public string? DeptDesc { get; set; }

    [Column("Dept_Location")]
    [StringLength(50)]
    public string? DeptLocation { get; set; }

    [Column("Dept_Manager")]
    public int? DeptManager { get; set; }

    [Column("Manager_hiredate")]
    public DateOnly? ManagerHiredate { get; set; }

    [ForeignKey("DeptManager")]
    [InverseProperty("Departments")]
    public virtual Instructor? DeptManagerNavigation { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    [InverseProperty("Dept")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}