// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCore_Lab_03.Models;

[Table("Instructor")]
public partial class Instructor
{
    [Key]
    [Column("Ins_Id")]
    public int InsId { get; set; }

    [Column("Ins_Name")]
    [StringLength(50)]
    public string? InsName { get; set; }

    [Column("Ins_Degree")]
    [StringLength(50)]
    public string? InsDegree { get; set; }

    [Column(TypeName = "money")]
    public decimal? Salary { get; set; }

    [Column("Dept_Id")]
    public int? DeptId { get; set; }

    [InverseProperty("DeptManagerNavigation")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    [ForeignKey("DeptId")]
    [InverseProperty("Instructors")]
    public virtual Department? Dept { get; set; }

    [InverseProperty("Ins")]
    public virtual ICollection<InsCourse> InsCourses { get; set; } = new List<InsCourse>();
}