// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using EFCore_Lab_03.Models;
using Microsoft.EntityFrameworkCore;

namespace EFCore_Lab_03.Context;

public partial class ITIDbContext : DbContext
{
    public ITIDbContext()
    {
    }

    public ITIDbContext(DbContextOptions<ITIDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<InsCourse> InsCourses { get; set; }

    public virtual DbSet<Instructor> Instructors { get; set; }

    public virtual DbSet<StudCourse> StudCourses { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=ITI;Integrated Security=True;Encrypt=False;TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.Property(e => e.CrsId).ValueGeneratedNever();

            entity.HasOne(d => d.Top).WithMany(p => p.Courses).HasConstraintName("FK_Course_Topic");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.ToTable("Department", tb => tb.HasTrigger("t2"));

            entity.Property(e => e.DeptId).ValueGeneratedNever();

            entity.HasOne(d => d.DeptManagerNavigation).WithMany(p => p.Departments).HasConstraintName("FK_Department_Instructor");
        });

        modelBuilder.Entity<InsCourse>(entity =>
        {
            entity.HasOne(d => d.Crs).WithMany(p => p.InsCourses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Ins_Course_Course");

            entity.HasOne(d => d.Ins).WithMany(p => p.InsCourses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Ins_Course_Instructor");
        });

        modelBuilder.Entity<Instructor>(entity =>
        {
            entity.Property(e => e.InsId).ValueGeneratedNever();

            entity.HasOne(d => d.Dept).WithMany(p => p.Instructors).HasConstraintName("FK_Instructor_Department");
        });

        modelBuilder.Entity<StudCourse>(entity =>
        {
            entity.HasOne(d => d.Crs).WithMany(p => p.StudCourses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Stud_Course_Course");

            entity.HasOne(d => d.St).WithMany(p => p.StudCourses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Stud_Course_Student");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.ToTable("Student", tb =>
                {
                    tb.HasTrigger("t5");
                    tb.HasTrigger("t6");
                });

            entity.Property(e => e.StId).ValueGeneratedNever();
            entity.Property(e => e.StLname).IsFixedLength();

            entity.HasOne(d => d.Dept).WithMany(p => p.Students).HasConstraintName("FK_Student_Department");

            entity.HasOne(d => d.StSuperNavigation).WithMany(p => p.InverseStSuperNavigation).HasConstraintName("FK_Student_Student");
        });

        modelBuilder.Entity<Topic>(entity =>
        {
            entity.Property(e => e.TopId).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}