// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCore_Lab_03.Models;

[Table("Student")]
public partial class Student
{
    [Key]
    [Column("St_Id")]
    public int StId { get; set; }

    [Column("St_Fname")]
    [StringLength(50)]
    public string? StFname { get; set; }

    [Column("St_Lname")]
    [StringLength(10)]
    public string? StLname { get; set; }

    [Column("St_Address")]
    [StringLength(100)]
    public string? StAddress { get; set; }

    [Column("St_Age")]
    public int? StAge { get; set; }

    [Column("Dept_Id")]
    public int? DeptId { get; set; }

    [Column("St_super")]
    public int? StSuper { get; set; }

    [StringLength(100)]
    public string? StEmail { get; set; }

    [ForeignKey("DeptId")]
    [InverseProperty("Students")]
    public virtual Department? Dept { get; set; }

    [InverseProperty("StSuperNavigation")]
    public virtual ICollection<Student> InverseStSuperNavigation { get; set; } = new List<Student>();

    [ForeignKey("StSuper")]
    [InverseProperty("InverseStSuperNavigation")]
    public virtual Student? StSuperNavigation { get; set; }

    [InverseProperty("St")]
    public virtual ICollection<StudCourse> StudCourses { get; set; } = new List<StudCourse>();
}